In [24]:
import numpy as np
import pandas as pd
pd.set_option('display.max_columns',None)
pd.set_option('display.max_rows',None)
import random

random.seed(5)

j_low=3 #ジョブ数の最小
j_high=10 #ジョブ数最大
p_low=3 #プロセス数の最小
p_high=8 #プロセス数最大
m_low=1 #最小機械番号
m_high=5 #最大機械番号
t_low=10 #最小プロセス時間
t_high=20 #最大プロセス時間

j_number=np.random.randint(j_low,j_high,1)#ジョブセットの中のジョブ数を固定
print('ジョブセットのジョブ数:',j_number)
p_number=np.zeros(j_number)#各ジョブのプロセス数を固定
#print('p_number:',p_number)
for i in np.arange(0,j_number):
    p_number[i]=np.random.randint(p_low,p_high,1)
print('各ジョブのプロセス数:',p_number)
p_number_max=max(p_number)
print('各ジョブの最大プロセス:',p_number_max)

MS_J=np.zeros((int(j_number),int(p_number_max)))
for i in np.arange(0,j_number):
    k=int(p_number[i])
    #print('今は',i+1,'行目，全部',k,'個プロセス')
    for j in np.arange(0,k):
        MS_J[i,j]=np.random.randint(m_low,m_high,1)
print('ジョブセットの機械番号:\n',MS_J)

T_J=np.zeros((int(j_number),int(p_number_max)))
for i in np.arange(0,j_number):
    k=int(p_number[i])
    #print('今は',i+1,'行目，全部',k,'個プロセス')
    for j in np.arange(0,k):
        T_J[i,j]=np.random.randint(t_low,t_high,1)
print('ジョブセットの操作時間:\n',T_J)

JOBSET_0=np.zeros((int(j_number),int(p_number_max)))
JOBSET=pd.DataFrame(JOBSET_0, columns=[f"process{i+1}" for i in range(int(p_number_max))], index=[f"job{i+1}" for i in range(int(j_number))])
JOBSET=JOBSET.astype(str)
#print(JOBSET)
for i in np.arange(0,j_number):
    k=int(p_number[i])
    for j in np.arange(0,k):
        m=MS_J[i,j]
        t=T_J[i,j]
        JOBSET.iloc[i,j]=str(m),str(t)
        
print('自動生成したジョブセット：\n',JOBSET)

#np.savetxt(fname='d:/pysrc/wang_data/automatic generate jobset.csv',X=JOBSET,fmt='%0d,%0d,%0d,%0d,%0d,%0d,%0d',delimiter=',')
JOBSET.to_csv('d:/pysrc/wang_data/automatic generate jobset.csv',index=True)

ジョブセットのジョブ数: [7]
各ジョブのプロセス数: [6. 7. 5. 3. 5. 4. 6.]
各ジョブの最大プロセス: 7.0
ジョブセットの機械番号:
 [[4. 1. 2. 1. 1. 2. 0.]
 [3. 3. 3. 4. 3. 1. 4.]
 [1. 1. 4. 2. 3. 0. 0.]
 [4. 2. 4. 0. 0. 0. 0.]
 [4. 3. 4. 2. 4. 0. 0.]
 [1. 4. 2. 2. 0. 0. 0.]
 [3. 2. 4. 3. 1. 3. 0.]]
ジョブセットの操作時間:
 [[12. 14. 12. 17. 10. 17.  0.]
 [13. 12. 12. 18. 17. 15. 13.]
 [11. 12. 17. 17. 16.  0.  0.]
 [17. 11. 15.  0.  0.  0.  0.]
 [11. 12. 18. 14. 13.  0.  0.]
 [16. 11. 12. 13.  0.  0.  0.]
 [18. 15. 15. 18. 10. 16.  0.]]
自動生成したジョブセット：
          process1     process2     process3     process4     process5  \
job1  (4.0, 12.0)  (1.0, 14.0)  (2.0, 12.0)  (1.0, 17.0)  (1.0, 10.0)   
job2  (3.0, 13.0)  (3.0, 12.0)  (3.0, 12.0)  (4.0, 18.0)  (3.0, 17.0)   
job3  (1.0, 11.0)  (1.0, 12.0)  (4.0, 17.0)  (2.0, 17.0)  (3.0, 16.0)   
job4  (4.0, 17.0)  (2.0, 11.0)  (4.0, 15.0)          0.0          0.0   
job5  (4.0, 11.0)  (3.0, 12.0)  (4.0, 18.0)  (2.0, 14.0)  (4.0, 13.0)   
job6  (1.0, 16.0)  (4.0, 11.0)  (2.0, 12.0)  (2.0, 13.0)       

C:\Users\G15\AppData\Local\Temp\ipykernel_23780\477844709.py:22: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  for i in np.arange(0,j_number):
C:\Users\G15\AppData\Local\Temp\ipykernel_23780\477844709.py:23: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  p_number[i]=np.random.randint(p_low,p_high,1)
C:\Users\G15\AppData\Local\Temp\ipykernel_23780\477844709.py:28: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  MS_J=np.zeros((int(j_number),int(p_number_max)))
C:\Users\